### ISSUE TITLE
Resetting heights on all nodes causes page to jump in some usecases/ add optional 'slaveNodes' prop

### ISSUE THREAD

**Issue by peterlenagh** [patrickgalbraith/react-equalizer#11]
I'm using equalizer to make a padder element the same height as a fixed position element.

```jsx
<Eq>
    <padder />
    <footer style={{ position: 'fixed' }} />
</Eq>
```

Resetting style.height on all nodes to calculate their natural height causes the padder to zero out briefly (it has no height of its own). In a fixed bottom footer use case such as mine this causes the page to scroll as it changes the page height. I guess this would affect other use cases too. 

I'd be interested in adding a `slaveNodes` prop, or something similar (with a better name), for nodes that only ever receive height and aren't used to calculate height.

Above, padder would be a slave, and would get its height based on its tallest sibling but never have its height set itself.

I can PR this if you're interested? Or I'll fork the plugin. unless you have another suggestion.

Thanks,

Pete

**Comment by patrickgalbraith** [comment]
See this commit 47a411e863c20f232ac67405fa740aa85d9ff55d

Is that what you are looking for?

Basically it would work something like:

```
<Equalizer nodeWillCompute={(node) => node.name != 'Padder'}>
  <Padder>Child 1</Padder>
  <div>Child 2</div>
  <div>Child 3</div>
</Equalizer>
```

I still need to add some tests for it but let me know if that is what you are after.

**Comment by peterlenagh** [comment]
sorry for ignoring your comment, i didn't see it. this would've done it yeh 😅
