### ISSUE TITLE
Recalculate Equalizer when height of content changes?

### ISSUE THREAD

**Issue by gtwilliams03** [patrickgalbraith/react-equalizer#13]
Is there a method to ask the equalizer to either monitor the height of a child element or recalculate when the height of a child `<div>` content changes?  I have some panels which load ajax content and the tables can grow or shrink by several rows and it would be nice to have the Equalizer resize when the content changes?  I haven't been able to figure out how to monitor this though.

**Comment by sjd78** [comment]
This equalizer depends on the `resize` event to initiate resizing.  See https://developer.mozilla.org/en-US/docs/Web/Events/resize for the event details.  Net result, only a document view resize will fire a change (for example, resizing the browser window), not content changes.

**Comment by gtwilliams03** [comment]
@sjd78 Thank you for your comment. Knowing that the `Equalizer` component only runs on the `resize` event, I added this to the callback on my ajax call and the columns resize nicely with the new data.

```
window.dispatchEvent(new Event('resize'))
```
