### ISSUE TITLE
Equalizer doesn't resize specifics nodes

### ISSUE THREAD

**Issue by iElsha** [patrickgalbraith/react-equalizer#14]
Hi,

I've got an issue when I try to use Equalizer with some specifics nodes
Here is the code :

`class Prestations extends Component {
	getNodes(equalizerComponet,equalizerElement){
		return [
			this.refs.node1,
			this.refs.node2,
			this.refs.node3
		]
	}

	render() {
		return (
			<Equalizer
				byRow={true}
				property="minHeight"
				enabled={() => window.matchMedia("(min-width: 400px)").matches}
				nodes={() => this.getNodes()}>
				<Col s={12} m={4} l={3} className={""}>
					<Card cardClass={""} img={parking} imgClass={"max_70 min_70"} contentfirst={""}
					      contentsecond={"Parking"} ref={n => this.node1 = n}/>
				</Col>
				<Col s={12} m={4} l={3} className={""}>
					<Card cardClass={""} img={travail_manuel} imgClass={"max_70 min_70"} contentfirst={""}
					      contentsecond={"Travail Manuel"} ref={n => this.node2 = n}/>
				</Col>
				<Col s={12} m={4} l={3} className={""}>
					<Card cardClass={""} img={acces_pmr} imgClass={"max_70 min_70"} contentfirst={""}
					      contentsecond={"Accès aux personnes à mobilité réduite"} ref={n => this.node3 = n}/>
				</Col>
			</Equalizer>
		)
	}
}
`

The 3 cards doesn't have the same sizes.
WhenI load the page n responsive mode and I change the width I get this message error :

**Comment by patrickgalbraith** [comment]
@iElsha did you resolve this issue already? Can you let me know what happened.

**Comment by iElsha** [comment]
Hello,

No I didn't. I close this issue because it's a duplicated. I don't know why 2 issues were opened.
I still have the problem.
