### ISSUE TITLE
Not compatible with React v0.15.*

### ISSUE THREAD

**Issue by allybee** [patrickgalbraith/react-equalizer#2]
Hello,

I'm wondering if you have plans to upgrade to React v0.15.*?

Thanks

**Comment by patrickgalbraith** [comment]
Hi Allyson,

I have tested it with React 0.15.2 and changed the React dependency to be a peerDependency so it should use 0.14.0 or above if it is already installed. 

For reference see ac353f16420f9ab812140d5c5bea077a7bb6c533

-Patrick
