### ISSUE TITLE
Package for direct browser consumption?

### ISSUE THREAD

**Issue by PEZ** [patrickgalbraith/react-equalizer#5]
Hello,

I tried to package this module for CLJSJS (http://cljsjs.github.io/) but ran into problems. Maybe because I'm quite unfamiliar with different packaging systems. I see that some other modules are packaged with a `dist/` directory containing the module for use directly in the browser. If this module is packaged that way, I think it will be easy peasy to make a CLJSJS distribution.

What say you?

Regards,
/P

**Comment by patrickgalbraith** [comment]
I don't know anything about CLSJS but based on what I have read you will just need to:

- Download the source files https://github.com/patrickgalbraith/react-equalizer/archive/master.zip
- `npm install`
- `npm run prepublish`

This will create a `lib` folder with the compiled sources.

Not sure about how CLSJS handles dependancies though so you are on your own there.

**Comment by patrickgalbraith** [comment]
Also FYI I don't plan on committing the compiled sources because it is a pain to deal with for a lot of reasons and bad practice when working with git.
